### ISSUE TITLE
Better Error messages

### ISSUE THREAD

**Issue by blkperl** [signalfx/signalfx-detector-syncer#4]
If you pass in the wrong credentialId you just get back a 400 client error with no useful error messages.

**Comment by mpetazzoni** [comment]
Is this actually an error handling issue in `signalfx-detector-syncer` (or in `signalfx-python`), or is the backend simply not returning a useful error message?

Can you try doing the failing API call manually and see what error message the server actually returns? It would indeed be a 400, but the server _should_ also be saying why it's an invalid request.

If it's not saying anything useful, that's an issue with our API though, not with this tool.

**Comment by blkperl** [comment]
@mpetazzoni I missed your response. How do I do call the failing API manually?

I think I meant this output is unclear

```
$ sfx-sync-detectors -n -a  https://api.signalfx.com  --token=FAKE_TOKEN signalfx/alerts
Traceback (most recent call last):
  File "/usr/local/bin/sfx-sync-detectors", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/signalfx_detector_syncer/__main__.py", line 49, in main
    client.sync(options.directory)
  File "/usr/local/lib/python2.7/site-packages/signalfx_detector_syncer/syncer.py", line 50, in sync
    from_signalfx = self.load_from_signalfx()
  File "/usr/local/lib/python2.7/site-packages/signalfx_detector_syncer/syncer.py", line 162, in load_from_signalfx
    self._client.get_detectors(tags=self._tags))))
  File "/usr/local/lib/python2.7/site-packages/signalfx/rest.py", line 367, in get_detectors
    resp.raise_for_status()
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.signalfx.com/v2/detector?tags=signalfx-detector-syncer&limit=100&offset=0
```

**Comment by csibar** [comment]
@mpetazzoni I had a SignalFlow error in my detector, validation did not fail using `--dry-run`, however I got a similar 400 HTTPError:
```
2018-04-24 14:02:53,484 |     INFO | Creating detector internal/services.yaml...
https://api.signalfx.com
Traceback (most recent call last):
  File "/usr/local/bin/sfx-sync-detectors", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/signalfx_detector_syncer/__main__.py", line 49, in main
    client.sync(options.directory)
  File "/Library/Python/2.7/site-packages/signalfx_detector_syncer/syncer.py", line 72, in sync
    self.create_detector(path, from_files[path])
  File "/Library/Python/2.7/site-packages/signalfx_detector_syncer/syncer.py", line 169, in create_detector
    created = self._client.create_detector(detector)
  File "/Library/Python/2.7/site-packages/signalfx/rest.py", line 401, in create_detector
    resp.raise_for_status()
  File "/Library/Python/2.7/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.signalfx.com/v2/detector
```

Here's the actual response from SignalFx API:
```json
{
  "code" : 400,
  "message" : "Error starting SignalFlow program (ref: Dbi9Y3SAgAA): [more than one publish() method has the same metric name.]"
}
```

It would have been helpful if it printed the `message`.

**Comment by mpetazzoni** [comment]
@csibar Absolutely. Do you think you'd some cycles to submit a PR for this?
