### ISSUE TITLE
Missing loader

### ISSUE THREAD

**Issue by EnriqueWood** [signalfx/signalfx-detector-syncer#8]
Starting from this dockerfile
```
FROM python:3.7.11-alpine
ADD ./* .
RUN pip install signalfx-detector-syncer
ENTRYPOINT sh
```
Then, executing this command: 
`sfx-sync-detectors -v --token <MY_TOKEN> -a https://api.signalfx.com .`

I always end up with this error message
```
2022-01-04 15:37:50,799 |     INFO | Loading detectors from //...
Traceback (most recent call last):
  File "/usr/local/bin/sfx-sync-detectors", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/signalfx_detector_syncer/__main__.py", line 49, in main
    client.sync(options.directory)
  File "/usr/local/lib/python3.7/site-packages/signalfx_detector_syncer/syncer.py", line 44, in sync
    from_files = self.load_files(base_path, self._filter_predicate)
  File "/usr/local/lib/python3.7/site-packages/signalfx_detector_syncer/syncer.py", line 99, in load_files
    detectors[path] = self._load_detector(base_path, path)
  File "/usr/local/lib/python3.7/site-packages/signalfx_detector_syncer/syncer.py", line 119, in _load_detector
    detector = _YamlDetectorLoader().load(path, contents)
  File "/usr/local/lib/python3.7/site-packages/signalfx_detector_syncer/syncer.py", line 217, in load
    detector = self.validate(self._load(path, contents))
  File "/usr/local/lib/python3.7/site-packages/signalfx_detector_syncer/syncer.py", line 258, in _load
    detector = yaml.load(docs[0])
TypeError: load() missing 1 required positional argument: 'Loader'
```

Why am I getting this error? I read the docs but I cannot find what I'm doing wrong here

**Comment by EnriqueWood** [comment]
I finally found a workaround. What happens is that the last version of PyYAML (6.0 at the moment) does not support the yaml.load() call without specifying the Loader. The solution was to install PyYAML 5.4.1 using `pip install PyYAML==5.4.1 signalfx-detector-syncer`. I will leave a pull request with that change in the requirements file so the current code keeps working for new people until it gets corrected properly.

**Comment by mpetazzoni** [comment]
Thanks for reporting @EnriqueWood. I made the fix locally; can't push at the moment as I've lost permissions on this repository. Let me figure out how to get them back :)
